language: node_js
node_js:
- "10"

sudo: required

services:
- docker

cache:
  directories:
  - node_modules

matrix:
  fast_finish: true

before_install:
- chmod +x ./parity/parity.sh && ./parity/parity.sh
- npm install -g npm
- npm install -g release-it greenkeeper-lockfile

before_script:
- greenkeeper-lockfile-update

script:
- npm test -- --timeout 10000
- npm run build

after_script:
- greenkeeper-lockfile-upload

notifications:
  email: false